language: python
env:

python: 
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE fastfood' -U postgres
  - psql -c 'CREATE DATABASE fastfood_test' -U postgres
script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls