language: python
env:
  DATABASE_URL="dbname='fastfood' host='localhost' port='5432' user='postgres' password='post123"
  DATABASE_TEST_URL="dbname='fastfoodtest' host='localhost' port='5432' user='postgres' password='1234'"
  CONFIG_TYPE="testing"

python: 
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE fastfood' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres

script:
  - nosetests --with-coverage --cover-package=app/tests/v1

after_success:
  - coveralls